### ISSUE TITLE
Rotation doesnt appear to be working

### ISSUE THREAD

**Issue by dprotter** [keflavich/gaussfitter#12]
Yeah, this is old and hasnt been updated in a year, but I thought I'd see if anyone is still checking in on it. 

Even when I set "rotate = True" I get rotation values of 0.0, and the im_out clearly isnt rotated. Even if I spin the purposefully ovoid input image there is no value to the rotation parameter. 
![screen shot 2017-09-28 at 4 47 32 pm](https://user-images.githubusercontent.com/12704406/30993560-c551a6de-a46c-11e7-8d09-661d8db5c47c.png)
Thanks!

**Comment by keflavich** [comment]
Any chance you could provide a minimum working example?  I'll try to fix it if I can find the error.

**Comment by dprotter** [comment]
Not sure the best way to go about this. I’m just a poor biochemist who does
image processing on the side.
I’ve attached two images (the same dot, rotated) to test this with.

Thanks so much, hope theres just some simple mistake I’m making.

Dave

**Comment by keflavich** [comment]
Could you just post some of the code used to produce those images?

**Comment by dprotter** [comment]
`import gaussfitter

from skimage import io
import matplotlib.pyplot as plt


fname1 = '/Users/davidprotter/Documents/Data/Dave Roton/LEA from Bhala/For Analysis/DotR.tif'
image1 = io.imread(fname1)
fname2 = '/Users/davidprotter/Documents/Data/Dave Roton/LEA from Bhala/For Analysis/DotR2.tif'
image2 = io.imread(fname2)

params1, im_out1 = gaussfitter.gaussfit(image1, rotate=True, returnfitimage=True)
params2, im_out2 = gaussfitter.gaussfit(image2, rotate=True, returnfitimage=True)

fig, ax = plt.subplots(ncols = 2,nrows = 2, figsize = (10,10))
ax[0][0].imshow(im_out1)
ax[0][0].set_title('Fit')
ax[0][1].imshow(image1)
ax[0][1].set_title('Input Image')

ax[1][0].imshow(im_out2)
ax[1][0].set_title('Fit')
ax[1][1].imshow(image2)
ax[1][1].set_title('Input Image')


plt.show()
print('Parameters 1: %s' %params1)
print('Parameters 2: %s' %params2)`


![figure_1-2](https://user-images.githubusercontent.com/12704406/31024724-2f8c47f8-a4fd-11e7-8fdd-db5fdbff7333.png)

**Comment by keflavich** [comment]
I see.  I believe the problem is that `skimage.io` is reading the file as `int` types.  Try changing 

`params1, im_out1 = gaussfitter.gaussfit(image1, rotate=True, returnfitimage=True)`
to
`params1, im_out1 = gaussfitter.gaussfit(image1.astype('float'), rotate=True, returnfitimage=True)`

**Comment by dprotter** [comment]
hmm tried it as float but still got the same result.

**Comment by keflavich** [comment]
Strange.  Are these TIF files actually monochrome?

**Comment by dprotter** [comment]
Yeah, here’s the raw data, if you want it.












array([[ 873,  883,  914,  892,  838,  867,  895,  880,  862,  885,  935,
         919,  920,  968,  927,  893,  890,  914,  923,  846,  916,  875,
         843,  796,  846,  829,  826,  817,  861],
       [ 822,  873,  948,  944,  893,  881,  968,  902,  898,  891,  977,
         927,  987,  914, 1001,  919,  911,  956,  935,  949,  913,  920,
         856,  818,  818,  853,  860,  823,  880],
       [ 865,  928,  927,  905,  929,  892,  907,  904,  917,  928,  974,
         929,  964, 1032,  996,  936,  965,  976,  932,  952,  935,  926,
         895,  843,  830,  805,  852,  848,  828],
       [ 929,  936,  948,  919,  933,  909,  904,  956,  969,  968,  977,
         945,  972, 1024,  988,  980,  987,  971,  938,  969,  963,  960,
         938,  872,  844,  850,  835,  846,  829],
       [ 917,  913,  953,  936,  925,  939,  953,  940,  909,  926,  967,
         974,  984, 1009, 1021,  992, 1008, 1041, 1044, 1073, 1023,  993,
         955,  927,  888,  846,  878,  878,  856],
       [ 906,  900,  865,  886,  938,  938,  940,  969, 1001,  957,  983,
        1008,  998,  995, 1072, 1081, 1121, 1155, 1103, 1070, 1104, 1052,
         991,  957,  924,  891,  954,  906,  868],
       [ 910,  895,  923,  925,  963,  927,  957,  993,  944,  933,  991,
        1038, 1026, 1032, 1178, 1151, 1287, 1324, 1332, 1367, 1356, 1247,
        1162, 1022, 1027,  904,  957,  895,  901],
       [ 945,  930,  935,  906,  963,  972, 1020, 1124, 1099,  996,  995,
        1131, 1079, 1182, 1222, 1270, 1467, 1684, 1900, 2035, 1991, 1763,
        1427, 1191, 1101,  985,  966,  949,  943],
       [ 929,  914, 1012,  992,  949, 1039, 1090, 1138, 1108, 1122, 1086,
        1230, 1195, 1298, 1439, 1519, 1825, 2353, 2955, 3437, 3330, 2726,
        1945, 1458, 1179, 1107, 1017,  921,  899],
       [ 946,  976,  981,  999, 1026, 1074, 1140, 1186, 1153, 1198, 1287,
        1308, 1332, 1454, 1593, 1892, 2532, 3431, 4388, 4995, 4815, 3938,
        2799, 1875, 1382, 1157, 1019,  958,  892],
       [ 993, 1024, 1013, 1083, 1106, 1135, 1241, 1318, 1319, 1372, 1472,
        1508, 1582, 1758, 2016, 2532, 3433, 4669, 5634, 6073, 5870, 4996,
        3574, 2283, 1512, 1078, 1029,  945,  911],
       [ 975, 1042, 1083, 1112, 1189, 1276, 1431, 1534, 1616, 1703, 1814,
        1924, 2108, 2429, 2827, 3394, 4445, 5716, 6531, 6764, 6357, 5437,
        3836, 2511, 1544, 1183, 1097,  978,  942],
       [ 976, 1033, 1075, 1177, 1364, 1491, 1706, 2031, 2160, 2358, 2528,
        2571, 2833, 3405, 4094, 4942, 5706, 6460, 7047, 6808, 6540, 5347,
        3613, 2429, 1569, 1224, 1040,  960,  921],
       [1020, 1093, 1102, 1208, 1371, 1662, 2112, 2804, 3330, 3569, 3461,
        3558, 3811, 4590, 5425, 6124, 6684, 6842, 6828, 6506, 5760, 4612,
        3149, 2161, 1543, 1240, 1093,  974,  920],
       [1009, 1069, 1192, 1317, 1549, 2036, 2718, 3485, 4262, 4751, 4752,
        4657, 4868, 5654, 6411, 6863, 7090, 6877, 6289, 5658, 4873, 3751,
        2683, 1925, 1447, 1212, 1096,  999,  938],
       [1029, 1138, 1199, 1400, 1814, 2494, 3384, 4290, 5193, 5619, 5648,
        5444, 5531, 6125, 6712, 7046, 6895, 6380, 5533, 4638, 3789, 2897,
        2175, 1669, 1382, 1176, 1022,  975,  911],
       [1097, 1169, 1276, 1564, 1989, 2829, 3961, 4928, 5741, 6252, 6222,
        5923, 5830, 6199, 6559, 6607, 6163, 5451, 4496, 3635, 2867, 2283,
        1831, 1485, 1261, 1170, 1089,  945,  905],
       [1088, 1158, 1292, 1562, 2137, 3142, 4382, 5320, 5945, 6393, 6318,
        6061, 5852, 5854, 5986, 5979, 5477, 4545, 3509, 2716, 2193, 1854,
        1607, 1367, 1148, 1127, 1045,  926,  894],
       [1062, 1164, 1338, 1639, 2128, 3208, 4487, 5383, 5976, 6343, 6170,
        5734, 5424, 5010, 4723, 4652, 4321, 3527, 2681, 2139, 1793, 1554,
        1350, 1227, 1087, 1064, 1042,  884,  900],
       [1050, 1141, 1326, 1670, 2063, 2917, 4210, 5189, 5787, 5963, 5738,
        5071, 4434, 3751, 3355, 3156, 2908, 2450, 1954, 1732, 1452, 1285,
        1225, 1082, 1018, 1017,  962,  920,  892],
       [1020, 1082, 1265, 1482, 1858, 2439, 3508, 4399, 4945, 4971, 4636,
        3958, 3285, 2668, 2357, 2160, 1941, 1731, 1553, 1422, 1284, 1222,
        1149, 1046,  966,  940,  924,  889,  873],
       [1037, 1075, 1190, 1340, 1618, 1966, 2575, 3167, 3571, 3624, 3309,
        2787, 2333, 1976, 1731, 1580, 1497, 1438, 1332, 1223, 1131, 1093,
        1043,  984,  917,  884,  881,  847,  814],
       [ 974, 1026, 1146, 1256, 1389, 1625, 1853, 2145, 2399, 2414, 2268,
        2013, 1744, 1579, 1476, 1337, 1247, 1239, 1119, 1126, 1057,  944,
         905,  926,  888,  859,  833,  859,  807],
       [ 913,  967, 1045, 1151, 1243, 1336, 1461, 1626, 1644, 1599, 1532,
        1486, 1426, 1337, 1313, 1172, 1148, 1117, 1017, 1018,  975,  878,
         886,  889,  871,  830,  792,  835,  844],
       [ 922,  935,  970, 1035, 1130, 1137, 1269, 1364, 1320, 1349, 1287,
        1204, 1206, 1118, 1148, 1086, 1051,  955,  979,  915,  946,  867,
         869,  841,  842,  821,  859,  779,  827],
       [ 875,  833,  906,  949,  892,  986, 1097, 1101, 1080, 1127, 1066,
        1057, 1045, 1014,  986,  951,  997,  894,  924,  867,  880,  866,
         802,  773,  803,  829,  818,  792,  792],
       [ 817,  797,  868,  885,  948,  992,  954,  967,  970,  981, 1045,
         975,  930,  950,  956,  955,  976,  922,  910,  871,  872,  833,
         759,  748,  758,  800,  841,  852,  800],
       [ 810,  840,  856,  884,  890,  885,  892,  938,  917,  918,  960,
         915,  876,  900,  906,  854,  863,  879,  856,  828,  808,  796,
         809,  745,  728,  746,  743,  748,  727],
       [ 776,  789,  820,  870,  872,  861,  868,  893,  882,  886,  887,
         867,  874,  871,  850,  790,  825,  801,  782,  736,  720,  722,
         781,  744,  732,  728,  744,  741,  715]], dtype=uint16)

**Comment by keflavich** [comment]
OK, weird, I can reproduce this now... but I don't understand it yet.

**Comment by dprotter** [comment]
Haha well let me know if it starts to make sense. Also if theres a good way
to tip you in beer over the internet.

**Comment by keflavich** [comment]
OK, I've... "solved" it.  There is something peculiar about this data set, and I really can't explain it, but for whatever reason the optimizer got stuck in a bad part of parameter space.  If you do:

```
pars,fitim = gaussfitter.gaussfit(data.astype('float'), rotate=True, quiet=False, returnfitimage=True, angle_guess=65.)
```
you should get a better answer, i.e.:
```
array([  8.59953154e+02,   6.60766546e+03,   1.39724925e+01,
         1.49168424e+01,   6.85171670e+00,   2.87412103e+00,
         6.12685978e+01])
```

![image](https://user-images.githubusercontent.com/143715/31037163-ce096846-a52c-11e7-90ab-e1aa68df3095.png)

I wish I had an explanation for it getting stuck at zero, but I'm afraid I don't.  It's probably just a natural problem of the linear-descent method: if it starts at a bad position, it may never converge to a good answer.

**Comment by dprotter** [comment]
Awesome, looks like it’s working for me with the same angle guess.

Thanks so much!

Dave

**Comment by RoyiAvital** [comment]
Maybe a good strategy is to have few starting points with different rotation angles.  
Something like `range(0, 180, 15)`?
